// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BilAPIDemo.model
{
    [Table("Bil")]
    public partial class Bil
    {
        [Key]
        [StringLength(20)]
        public string Stelnummer { get; set; }
        [Required]
        [StringLength(30)]
        public string Model { get; set; }
        public int Km { get; set; }
        public int Aar { get; set; }
        [Required]
        [StringLength(20)]
        public string Maerke { get; set; }
        [Required]
        [StringLength(40)]
        public string Braendsel { get; set; }
    }
}